name: py3_miob
channels:
- defaults
dependencies:
- pip:
  - et-xmlfile==1.0.1
  - ipython-genutils==0.2.0
  - jdcal==1.3
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - lxml==4.0.0
  - numpy==1.13.1
  - openpyxl==2.4.8
  - pandas==0.20.3
  - prompt-toolkit==1.0.15
  - pytz==2017.2
  - xlrd==1.1.0

